# Generated by Django 5.1.3 on 2024-11-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comments_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='parents',
            new_name='parent',
        ),
    ]
